# Generated by Django 2.2.3 on 2019-07-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190722_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
