# Generated by Django 2.2.3 on 2019-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_postrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postrecord',
            old_name='title',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='postrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postrecord',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postrecord',
            name='post_created_at',
        ),
        migrations.AddField(
            model_name='postrecord',
            name='product_description',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postrecord',
            name='product_image',
            field=models.ImageField(blank=True, default='photos/TV.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='postrecord',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postrecord',
            name='remain_product',
            field=models.IntegerField(default=0),
        ),
    ]
