# Generated by Django 2.2.3 on 2019-07-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190723_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postrecord',
        ),
    ]
