# Generated by Django 2.2.3 on 2019-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_postrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_less',
            field=models.TextField(blank=True),
        ),
    ]
